// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDWhcJdL_ZDt6l-SpnwjTxJpWaL8ylHKY',
    appId: '1:661890890825:web:4f87b270a03b8a18471398',
    messagingSenderId: '661890890825',
    projectId: 'chat-app-39880',
    authDomain: 'chat-app-39880.firebaseapp.com',
    storageBucket: 'chat-app-39880.appspot.com',
    measurementId: 'G-P1WBC6KXF3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKNOvXdneRWVwwFn5bKBPR0TK9VyLFrE0',
    appId: '1:661890890825:android:300b1c918b2cb8d2471398',
    messagingSenderId: '661890890825',
    projectId: 'chat-app-39880',
    storageBucket: 'chat-app-39880.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAOEKa-itSVuxVjRSvJSWfP_uWQhqziO6Q',
    appId: '1:661890890825:ios:2cf8ea2e3821dede471398',
    messagingSenderId: '661890890825',
    projectId: 'chat-app-39880',
    storageBucket: 'chat-app-39880.appspot.com',
    iosBundleId: 'com.example.chatapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAOEKa-itSVuxVjRSvJSWfP_uWQhqziO6Q',
    appId: '1:661890890825:ios:41d7beb80d1928e6471398',
    messagingSenderId: '661890890825',
    projectId: 'chat-app-39880',
    storageBucket: 'chat-app-39880.appspot.com',
    iosBundleId: 'com.example.chatapp.RunnerTests',
  );
}
